### ISSUE TITLE
Issue with blockquotes

### ISSUE THREAD

**Issue by mirkoschubert** [outflux3/InputfieldSimpleMDE#1]
Hi, great module! Loving it so far.
But I have found an issue with blockquotes. It doesn't translate into code wether I write the markdown myself or click the icon. In the frontend the blockquote isn't shown in html as well. I use the textformatter Parsedown Extra, but I also checked it with Parsedown.
I just checked if there's an issue filed in the original SimpleMDE, but I didn't found any.

**Comment by outflux3** [comment]
The blockquote works for me and also shows as a blockquote in the front end, using the Parsedown Extra. Could maybe be the PW version
