### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by DanMan** [outflux3/InputfieldSimpleMDE#7]
The editor currently only shows up for the first field.

**Comment by outflux3** [comment]
ok thanks for the report, will look into it.

**Comment by outflux3** [comment]
Should work now:

https://github.com/outflux3/InputfieldSimpleMDE/commit/d8eab8ad345d5961ab4ae65c7272bf281e5b5728

**Comment by DanMan** [comment]
Nope. Still only shows up for the first language. If I switch to a different language tab, there's no editor.

**Comment by outflux3** [comment]
it works here on all the tabs, what PW version are you on?

**Comment by DanMan** [comment]
Installed v3.0.98 freshly on Wednesday.

**Comment by outflux3** [comment]
Works fine here, are you sure you refreshed the modules and you are not caching the js file?

**Comment by DanMan** [comment]
If I inspect the JS in the page, I can see the `tabsactivate` that you added to `InputfieldSimpleMDE.js`. I also just re-installed InputfieldSimpleMDE and it still doesn't work.

**Comment by outflux3** [comment]
thanks, yeah, it is a theme issue, it works on Reno, possibly default, but not currently on UiKit; a fix is in progress, thanks again for your report.

**Comment by DanMan** [comment]
You're right. It works on "default". Thanks for looking into it.

**Comment by outflux3** [comment]
should work now on UiKit

https://github.com/outflux3/InputfieldSimpleMDE/commit/209b0e2b163d39157c99d2e80dff9889969d1ddd
