### ISSUE TITLE
Page will not be saved if InputfieldSimpleMDE field has html5 required option

### ISSUE THREAD

**Issue by tiefenb** [outflux3/InputfieldSimpleMDE#8]
PW: 3.0.127

If a field with InputfieldSimpleMDE as the required option and also the html5 required option, the page can't be saved and in the console there is an exception. Also if the field as data.

<img width="1387" alt="Bildschirmfoto 2019-03-21 um 11 31 03" src="https://user-images.githubusercontent.com/488163/54747013-fc9c6e80-4bcd-11e9-8e85-34c3ca2c7be5.png">
<img width="1440" alt="Bildschirmfoto 2019-03-21 um 11 29 13" src="https://user-images.githubusercontent.com/488163/54747014-fc9c6e80-4bcd-11e9-8498-b1a95d9b5dc5.png">

**Comment by outflux3** [comment]
I'm pretty sure we're just using the plain field, so this would be an issue of that:

https://github.com/sparksuite/simplemde-markdown-editor/issues/324

https://github.com/sparksuite/simplemde-markdown-editor/issues/484

one person suggested this as a workaround, which you could add in your custom js for the admin:

$('#original-text-area').attr('required', false); $('.CodeMirror textarea').attr('required', true);
